webservers:
  hosts:
    webserver01:
      ansible_host: "{{ lookup('env', 'ANSIBLE_HOST', default='') | default(omit) }}"
      ansible_ssh_private_key_file: "~/.ssh/id_rsa"
      ansible_user: "{{ lookup('env', 'ANSIBLE_USER', default='') | default(omit) }}"